// <auto-generated />
using System;
using HaverProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HaverProject.Data.HMigrations
{
    [DbContext(typeof(HaverContext))]
    partial class HaverContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.16");

            modelBuilder.Entity("HaverProject.Models.NCR", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CARNo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CARYes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CustomerNO")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CustomerYes")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DeferforHBC")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescriptionDefect")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionItem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Disposition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DrawingNo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DrawingYes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Engineer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EngineerDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("FollowupNo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FollowupYes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NCRNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameOfEngineer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("No")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OperatingManagerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalRev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("PONumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreliminaryDecision")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantityDefected")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityReceived")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Repair")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RepresentativesName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ReturntoSupplier")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RevisingDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Rework")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReworkInHouse")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Scrap")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ScrapinHouse")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SupplierOrRecInsp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedRev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseAsIs")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WIP")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Yes")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Ncrs");
                });
#pragma warning restore 612, 618
        }
    }
}
